/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShopifyRouteImport } from './routes/_authenticated/shopify'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as ApiShopifyTestConnectionRouteImport } from './routes/api/shopify/test-connection'
import { Route as ApiShopifySyncStatusRouteImport } from './routes/api/shopify/sync-status'
import { Route as ApiShopifySyncProductsRouteImport } from './routes/api/shopify/sync-products'
import { Route as ApiShopifySyncOrdersRouteImport } from './routes/api/shopify/sync-orders'
import { Route as ApiShopifySyncInventoryCostRouteImport } from './routes/api/shopify/sync-inventory-cost'
import { Route as ApiShopifyResetAndSync2026OrdersRouteImport } from './routes/api/shopify/reset-and-sync-2026-orders'
import { Route as ApiOrdersResetAllRouteImport } from './routes/api/orders/reset-all'
import { Route as ApiPublicShopifyWebhooksOrdersUpdatedRouteImport } from './routes/api/public/shopify/webhooks/orders-updated'
import { Route as ApiPublicShopifyWebhooksOrdersCreateRouteImport } from './routes/api/public/shopify/webhooks/orders-create'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShopifyRoute = AuthenticatedShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiShopifyTestConnectionRoute =
  ApiShopifyTestConnectionRouteImport.update({
    id: '/api/shopify/test-connection',
    path: '/api/shopify/test-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifySyncStatusRoute = ApiShopifySyncStatusRouteImport.update({
  id: '/api/shopify/sync-status',
  path: '/api/shopify/sync-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifySyncProductsRoute = ApiShopifySyncProductsRouteImport.update({
  id: '/api/shopify/sync-products',
  path: '/api/shopify/sync-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifySyncOrdersRoute = ApiShopifySyncOrdersRouteImport.update({
  id: '/api/shopify/sync-orders',
  path: '/api/shopify/sync-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifySyncInventoryCostRoute =
  ApiShopifySyncInventoryCostRouteImport.update({
    id: '/api/shopify/sync-inventory-cost',
    path: '/api/shopify/sync-inventory-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyResetAndSync2026OrdersRoute =
  ApiShopifyResetAndSync2026OrdersRouteImport.update({
    id: '/api/shopify/reset-and-sync-2026-orders',
    path: '/api/shopify/reset-and-sync-2026-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersResetAllRoute = ApiOrdersResetAllRouteImport.update({
  id: '/api/orders/reset-all',
  path: '/api/orders/reset-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShopifyWebhooksOrdersUpdatedRoute =
  ApiPublicShopifyWebhooksOrdersUpdatedRouteImport.update({
    id: '/api/public/shopify/webhooks/orders-updated',
    path: '/api/public/shopify/webhooks/orders-updated',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksOrdersCreateRoute =
  ApiPublicShopifyWebhooksOrdersCreateRouteImport.update({
    id: '/api/public/shopify/webhooks/orders-create',
    path: '/api/public/shopify/webhooks/orders-create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/import': typeof AuthenticatedImportRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shopify': typeof AuthenticatedShopifyRoute
  '/api/orders/reset-all': typeof ApiOrdersResetAllRoute
  '/api/shopify/reset-and-sync-2026-orders': typeof ApiShopifyResetAndSync2026OrdersRoute
  '/api/shopify/sync-inventory-cost': typeof ApiShopifySyncInventoryCostRoute
  '/api/shopify/sync-orders': typeof ApiShopifySyncOrdersRoute
  '/api/shopify/sync-products': typeof ApiShopifySyncProductsRoute
  '/api/shopify/sync-status': typeof ApiShopifySyncStatusRoute
  '/api/shopify/test-connection': typeof ApiShopifyTestConnectionRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-updated': typeof ApiPublicShopifyWebhooksOrdersUpdatedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/import': typeof AuthenticatedImportRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shopify': typeof AuthenticatedShopifyRoute
  '/api/orders/reset-all': typeof ApiOrdersResetAllRoute
  '/api/shopify/reset-and-sync-2026-orders': typeof ApiShopifyResetAndSync2026OrdersRoute
  '/api/shopify/sync-inventory-cost': typeof ApiShopifySyncInventoryCostRoute
  '/api/shopify/sync-orders': typeof ApiShopifySyncOrdersRoute
  '/api/shopify/sync-products': typeof ApiShopifySyncProductsRoute
  '/api/shopify/sync-status': typeof ApiShopifySyncStatusRoute
  '/api/shopify/test-connection': typeof ApiShopifyTestConnectionRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-updated': typeof ApiPublicShopifyWebhooksOrdersUpdatedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shopify': typeof AuthenticatedShopifyRoute
  '/api/orders/reset-all': typeof ApiOrdersResetAllRoute
  '/api/shopify/reset-and-sync-2026-orders': typeof ApiShopifyResetAndSync2026OrdersRoute
  '/api/shopify/sync-inventory-cost': typeof ApiShopifySyncInventoryCostRoute
  '/api/shopify/sync-orders': typeof ApiShopifySyncOrdersRoute
  '/api/shopify/sync-products': typeof ApiShopifySyncProductsRoute
  '/api/shopify/sync-status': typeof ApiShopifySyncStatusRoute
  '/api/shopify/test-connection': typeof ApiShopifyTestConnectionRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-updated': typeof ApiPublicShopifyWebhooksOrdersUpdatedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/areas'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/import'
    | '/inventory'
    | '/orders'
    | '/settings'
    | '/shopify'
    | '/api/orders/reset-all'
    | '/api/shopify/reset-and-sync-2026-orders'
    | '/api/shopify/sync-inventory-cost'
    | '/api/shopify/sync-orders'
    | '/api/shopify/sync-products'
    | '/api/shopify/sync-status'
    | '/api/shopify/test-connection'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-updated'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/areas'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/import'
    | '/inventory'
    | '/orders'
    | '/settings'
    | '/shopify'
    | '/api/orders/reset-all'
    | '/api/shopify/reset-and-sync-2026-orders'
    | '/api/shopify/sync-inventory-cost'
    | '/api/shopify/sync-orders'
    | '/api/shopify/sync-products'
    | '/api/shopify/sync-status'
    | '/api/shopify/test-connection'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-updated'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/areas'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/import'
    | '/_authenticated/inventory'
    | '/_authenticated/orders'
    | '/_authenticated/settings'
    | '/_authenticated/shopify'
    | '/api/orders/reset-all'
    | '/api/shopify/reset-and-sync-2026-orders'
    | '/api/shopify/sync-inventory-cost'
    | '/api/shopify/sync-orders'
    | '/api/shopify/sync-products'
    | '/api/shopify/sync-status'
    | '/api/shopify/test-connection'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-updated'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiOrdersResetAllRoute: typeof ApiOrdersResetAllRoute
  ApiShopifyResetAndSync2026OrdersRoute: typeof ApiShopifyResetAndSync2026OrdersRoute
  ApiShopifySyncInventoryCostRoute: typeof ApiShopifySyncInventoryCostRoute
  ApiShopifySyncOrdersRoute: typeof ApiShopifySyncOrdersRoute
  ApiShopifySyncProductsRoute: typeof ApiShopifySyncProductsRoute
  ApiShopifySyncStatusRoute: typeof ApiShopifySyncStatusRoute
  ApiShopifyTestConnectionRoute: typeof ApiShopifyTestConnectionRoute
  ApiPublicShopifyWebhooksOrdersCreateRoute: typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  ApiPublicShopifyWebhooksOrdersUpdatedRoute: typeof ApiPublicShopifyWebhooksOrdersUpdatedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shopify': {
      id: '/_authenticated/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof AuthenticatedShopifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/shopify/test-connection': {
      id: '/api/shopify/test-connection'
      path: '/api/shopify/test-connection'
      fullPath: '/api/shopify/test-connection'
      preLoaderRoute: typeof ApiShopifyTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/sync-status': {
      id: '/api/shopify/sync-status'
      path: '/api/shopify/sync-status'
      fullPath: '/api/shopify/sync-status'
      preLoaderRoute: typeof ApiShopifySyncStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/sync-products': {
      id: '/api/shopify/sync-products'
      path: '/api/shopify/sync-products'
      fullPath: '/api/shopify/sync-products'
      preLoaderRoute: typeof ApiShopifySyncProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/sync-orders': {
      id: '/api/shopify/sync-orders'
      path: '/api/shopify/sync-orders'
      fullPath: '/api/shopify/sync-orders'
      preLoaderRoute: typeof ApiShopifySyncOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/sync-inventory-cost': {
      id: '/api/shopify/sync-inventory-cost'
      path: '/api/shopify/sync-inventory-cost'
      fullPath: '/api/shopify/sync-inventory-cost'
      preLoaderRoute: typeof ApiShopifySyncInventoryCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/reset-and-sync-2026-orders': {
      id: '/api/shopify/reset-and-sync-2026-orders'
      path: '/api/shopify/reset-and-sync-2026-orders'
      fullPath: '/api/shopify/reset-and-sync-2026-orders'
      preLoaderRoute: typeof ApiShopifyResetAndSync2026OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/reset-all': {
      id: '/api/orders/reset-all'
      path: '/api/orders/reset-all'
      fullPath: '/api/orders/reset-all'
      preLoaderRoute: typeof ApiOrdersResetAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/orders-updated': {
      id: '/api/public/shopify/webhooks/orders-updated'
      path: '/api/public/shopify/webhooks/orders-updated'
      fullPath: '/api/public/shopify/webhooks/orders-updated'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksOrdersUpdatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/orders-create': {
      id: '/api/public/shopify/webhooks/orders-create'
      path: '/api/public/shopify/webhooks/orders-create'
      fullPath: '/api/public/shopify/webhooks/orders-create'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksOrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShopifyRoute: typeof AuthenticatedShopifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShopifyRoute: AuthenticatedShopifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiOrdersResetAllRoute: ApiOrdersResetAllRoute,
  ApiShopifyResetAndSync2026OrdersRoute: ApiShopifyResetAndSync2026OrdersRoute,
  ApiShopifySyncInventoryCostRoute: ApiShopifySyncInventoryCostRoute,
  ApiShopifySyncOrdersRoute: ApiShopifySyncOrdersRoute,
  ApiShopifySyncProductsRoute: ApiShopifySyncProductsRoute,
  ApiShopifySyncStatusRoute: ApiShopifySyncStatusRoute,
  ApiShopifyTestConnectionRoute: ApiShopifyTestConnectionRoute,
  ApiPublicShopifyWebhooksOrdersCreateRoute:
    ApiPublicShopifyWebhooksOrdersCreateRoute,
  ApiPublicShopifyWebhooksOrdersUpdatedRoute:
    ApiPublicShopifyWebhooksOrdersUpdatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
