/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedShopifyRouteImport } from './routes/_authenticated/shopify'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as ApiShopifyTestConnectionRouteImport } from './routes/api/shopify/test-connection'
import { Route as ApiShopifySyncStatusRouteImport } from './routes/api/shopify/sync-status'
import { Route as ApiShopifySyncProductsRouteImport } from './routes/api/shopify/sync-products'
import { Route as ApiShopifySyncOrdersRouteImport } from './routes/api/shopify/sync-orders'
import { Route as ApiShopifySyncInventoryCostRouteImport } from './routes/api/shopify/sync-inventory-cost'
import { Route as ApiShopifyResetAndSync2026OrdersRouteImport } from './routes/api/shopify/reset-and-sync-2026-orders'
import { Route as ApiShopifyRepairUnknownCustomersRouteImport } from './routes/api/shopify/repair-unknown-customers'
import { Route as ApiShopifyRepairMissingOrderLineItemsRouteImport } from './routes/api/shopify/repair-missing-order-line-items'
import { Route as ApiShopifyRefreshOrderItemProductDataRouteImport } from './routes/api/shopify/refresh-order-item-product-data'
import { Route as ApiShopifyRefreshInventorySourceOfTruthRouteImport } from './routes/api/shopify/refresh-inventory-source-of-truth'
import { Route as ApiShopifyRecalculateOrderCostsRouteImport } from './routes/api/shopify/recalculate-order-costs'
import { Route as ApiShopifyInventoryReconciliationRouteImport } from './routes/api/shopify/inventory-reconciliation'
import { Route as ApiShopifyForceUpdateOrderItemCostsRouteImport } from './routes/api/shopify/force-update-order-item-costs'
import { Route as ApiShopifyBackfillOrderItemCostsRouteImport } from './routes/api/shopify/backfill-order-item-costs'
import { Route as ApiShopifyAutoRemapSuggestRouteImport } from './routes/api/shopify/auto-remap-suggest'
import { Route as ApiOrdersUpdateCostsRouteImport } from './routes/api/orders/update-costs'
import { Route as ApiOrdersRestoreLineItemsRouteImport } from './routes/api/orders/restore-line-items'
import { Route as ApiOrdersResetAllRouteImport } from './routes/api/orders/reset-all'
import { Route as ApiOrdersItemsRouteImport } from './routes/api/orders/items'
import { Route as ApiOrdersExternalOrderIntakeStatusRouteImport } from './routes/api/orders/external-order-intake-status'
import { Route as ApiOrdersExternalOrderIntakeRouteImport } from './routes/api/orders/external-order-intake'
import { Route as ApiOrdersApplyPendingIntakeRouteImport } from './routes/api/orders/apply-pending-intake'
import { Route as ApiFinanceUnlockRouteImport } from './routes/api/finance/unlock'
import { Route as ApiAuthEnsureSignupProfileRouteImport } from './routes/api/auth/ensure-signup-profile'
import { Route as ApiPublicShopifyWebhooksOrdersUpdatedRouteImport } from './routes/api/public/shopify/webhooks/orders-updated'
import { Route as ApiPublicShopifyWebhooksOrdersCreateRouteImport } from './routes/api/public/shopify/webhooks/orders-create'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShopifyRoute = AuthenticatedShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiShopifyTestConnectionRoute =
  ApiShopifyTestConnectionRouteImport.update({
    id: '/api/shopify/test-connection',
    path: '/api/shopify/test-connection',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifySyncStatusRoute = ApiShopifySyncStatusRouteImport.update({
  id: '/api/shopify/sync-status',
  path: '/api/shopify/sync-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifySyncProductsRoute = ApiShopifySyncProductsRouteImport.update({
  id: '/api/shopify/sync-products',
  path: '/api/shopify/sync-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifySyncOrdersRoute = ApiShopifySyncOrdersRouteImport.update({
  id: '/api/shopify/sync-orders',
  path: '/api/shopify/sync-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopifySyncInventoryCostRoute =
  ApiShopifySyncInventoryCostRouteImport.update({
    id: '/api/shopify/sync-inventory-cost',
    path: '/api/shopify/sync-inventory-cost',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyResetAndSync2026OrdersRoute =
  ApiShopifyResetAndSync2026OrdersRouteImport.update({
    id: '/api/shopify/reset-and-sync-2026-orders',
    path: '/api/shopify/reset-and-sync-2026-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyRepairUnknownCustomersRoute =
  ApiShopifyRepairUnknownCustomersRouteImport.update({
    id: '/api/shopify/repair-unknown-customers',
    path: '/api/shopify/repair-unknown-customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyRepairMissingOrderLineItemsRoute =
  ApiShopifyRepairMissingOrderLineItemsRouteImport.update({
    id: '/api/shopify/repair-missing-order-line-items',
    path: '/api/shopify/repair-missing-order-line-items',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyRefreshOrderItemProductDataRoute =
  ApiShopifyRefreshOrderItemProductDataRouteImport.update({
    id: '/api/shopify/refresh-order-item-product-data',
    path: '/api/shopify/refresh-order-item-product-data',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyRefreshInventorySourceOfTruthRoute =
  ApiShopifyRefreshInventorySourceOfTruthRouteImport.update({
    id: '/api/shopify/refresh-inventory-source-of-truth',
    path: '/api/shopify/refresh-inventory-source-of-truth',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyRecalculateOrderCostsRoute =
  ApiShopifyRecalculateOrderCostsRouteImport.update({
    id: '/api/shopify/recalculate-order-costs',
    path: '/api/shopify/recalculate-order-costs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyInventoryReconciliationRoute =
  ApiShopifyInventoryReconciliationRouteImport.update({
    id: '/api/shopify/inventory-reconciliation',
    path: '/api/shopify/inventory-reconciliation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyForceUpdateOrderItemCostsRoute =
  ApiShopifyForceUpdateOrderItemCostsRouteImport.update({
    id: '/api/shopify/force-update-order-item-costs',
    path: '/api/shopify/force-update-order-item-costs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyBackfillOrderItemCostsRoute =
  ApiShopifyBackfillOrderItemCostsRouteImport.update({
    id: '/api/shopify/backfill-order-item-costs',
    path: '/api/shopify/backfill-order-item-costs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShopifyAutoRemapSuggestRoute =
  ApiShopifyAutoRemapSuggestRouteImport.update({
    id: '/api/shopify/auto-remap-suggest',
    path: '/api/shopify/auto-remap-suggest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersUpdateCostsRoute = ApiOrdersUpdateCostsRouteImport.update({
  id: '/api/orders/update-costs',
  path: '/api/orders/update-costs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRestoreLineItemsRoute =
  ApiOrdersRestoreLineItemsRouteImport.update({
    id: '/api/orders/restore-line-items',
    path: '/api/orders/restore-line-items',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersResetAllRoute = ApiOrdersResetAllRouteImport.update({
  id: '/api/orders/reset-all',
  path: '/api/orders/reset-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersItemsRoute = ApiOrdersItemsRouteImport.update({
  id: '/api/orders/items',
  path: '/api/orders/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersExternalOrderIntakeStatusRoute =
  ApiOrdersExternalOrderIntakeStatusRouteImport.update({
    id: '/api/orders/external-order-intake-status',
    path: '/api/orders/external-order-intake-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersExternalOrderIntakeRoute =
  ApiOrdersExternalOrderIntakeRouteImport.update({
    id: '/api/orders/external-order-intake',
    path: '/api/orders/external-order-intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOrdersApplyPendingIntakeRoute =
  ApiOrdersApplyPendingIntakeRouteImport.update({
    id: '/api/orders/apply-pending-intake',
    path: '/api/orders/apply-pending-intake',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFinanceUnlockRoute = ApiFinanceUnlockRouteImport.update({
  id: '/api/finance/unlock',
  path: '/api/finance/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthEnsureSignupProfileRoute =
  ApiAuthEnsureSignupProfileRouteImport.update({
    id: '/api/auth/ensure-signup-profile',
    path: '/api/auth/ensure-signup-profile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksOrdersUpdatedRoute =
  ApiPublicShopifyWebhooksOrdersUpdatedRouteImport.update({
    id: '/api/public/shopify/webhooks/orders-updated',
    path: '/api/public/shopify/webhooks/orders-updated',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicShopifyWebhooksOrdersCreateRoute =
  ApiPublicShopifyWebhooksOrdersCreateRouteImport.update({
    id: '/api/public/shopify/webhooks/orders-create',
    path: '/api/public/shopify/webhooks/orders-create',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/import': typeof AuthenticatedImportRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shopify': typeof AuthenticatedShopifyRoute
  '/api/auth/ensure-signup-profile': typeof ApiAuthEnsureSignupProfileRoute
  '/api/finance/unlock': typeof ApiFinanceUnlockRoute
  '/api/orders/apply-pending-intake': typeof ApiOrdersApplyPendingIntakeRoute
  '/api/orders/external-order-intake': typeof ApiOrdersExternalOrderIntakeRoute
  '/api/orders/external-order-intake-status': typeof ApiOrdersExternalOrderIntakeStatusRoute
  '/api/orders/items': typeof ApiOrdersItemsRoute
  '/api/orders/reset-all': typeof ApiOrdersResetAllRoute
  '/api/orders/restore-line-items': typeof ApiOrdersRestoreLineItemsRoute
  '/api/orders/update-costs': typeof ApiOrdersUpdateCostsRoute
  '/api/shopify/auto-remap-suggest': typeof ApiShopifyAutoRemapSuggestRoute
  '/api/shopify/backfill-order-item-costs': typeof ApiShopifyBackfillOrderItemCostsRoute
  '/api/shopify/force-update-order-item-costs': typeof ApiShopifyForceUpdateOrderItemCostsRoute
  '/api/shopify/inventory-reconciliation': typeof ApiShopifyInventoryReconciliationRoute
  '/api/shopify/recalculate-order-costs': typeof ApiShopifyRecalculateOrderCostsRoute
  '/api/shopify/refresh-inventory-source-of-truth': typeof ApiShopifyRefreshInventorySourceOfTruthRoute
  '/api/shopify/refresh-order-item-product-data': typeof ApiShopifyRefreshOrderItemProductDataRoute
  '/api/shopify/repair-missing-order-line-items': typeof ApiShopifyRepairMissingOrderLineItemsRoute
  '/api/shopify/repair-unknown-customers': typeof ApiShopifyRepairUnknownCustomersRoute
  '/api/shopify/reset-and-sync-2026-orders': typeof ApiShopifyResetAndSync2026OrdersRoute
  '/api/shopify/sync-inventory-cost': typeof ApiShopifySyncInventoryCostRoute
  '/api/shopify/sync-orders': typeof ApiShopifySyncOrdersRoute
  '/api/shopify/sync-products': typeof ApiShopifySyncProductsRoute
  '/api/shopify/sync-status': typeof ApiShopifySyncStatusRoute
  '/api/shopify/test-connection': typeof ApiShopifyTestConnectionRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-updated': typeof ApiPublicShopifyWebhooksOrdersUpdatedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/import': typeof AuthenticatedImportRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/shopify': typeof AuthenticatedShopifyRoute
  '/api/auth/ensure-signup-profile': typeof ApiAuthEnsureSignupProfileRoute
  '/api/finance/unlock': typeof ApiFinanceUnlockRoute
  '/api/orders/apply-pending-intake': typeof ApiOrdersApplyPendingIntakeRoute
  '/api/orders/external-order-intake': typeof ApiOrdersExternalOrderIntakeRoute
  '/api/orders/external-order-intake-status': typeof ApiOrdersExternalOrderIntakeStatusRoute
  '/api/orders/items': typeof ApiOrdersItemsRoute
  '/api/orders/reset-all': typeof ApiOrdersResetAllRoute
  '/api/orders/restore-line-items': typeof ApiOrdersRestoreLineItemsRoute
  '/api/orders/update-costs': typeof ApiOrdersUpdateCostsRoute
  '/api/shopify/auto-remap-suggest': typeof ApiShopifyAutoRemapSuggestRoute
  '/api/shopify/backfill-order-item-costs': typeof ApiShopifyBackfillOrderItemCostsRoute
  '/api/shopify/force-update-order-item-costs': typeof ApiShopifyForceUpdateOrderItemCostsRoute
  '/api/shopify/inventory-reconciliation': typeof ApiShopifyInventoryReconciliationRoute
  '/api/shopify/recalculate-order-costs': typeof ApiShopifyRecalculateOrderCostsRoute
  '/api/shopify/refresh-inventory-source-of-truth': typeof ApiShopifyRefreshInventorySourceOfTruthRoute
  '/api/shopify/refresh-order-item-product-data': typeof ApiShopifyRefreshOrderItemProductDataRoute
  '/api/shopify/repair-missing-order-line-items': typeof ApiShopifyRepairMissingOrderLineItemsRoute
  '/api/shopify/repair-unknown-customers': typeof ApiShopifyRepairUnknownCustomersRoute
  '/api/shopify/reset-and-sync-2026-orders': typeof ApiShopifyResetAndSync2026OrdersRoute
  '/api/shopify/sync-inventory-cost': typeof ApiShopifySyncInventoryCostRoute
  '/api/shopify/sync-orders': typeof ApiShopifySyncOrdersRoute
  '/api/shopify/sync-products': typeof ApiShopifySyncProductsRoute
  '/api/shopify/sync-status': typeof ApiShopifySyncStatusRoute
  '/api/shopify/test-connection': typeof ApiShopifyTestConnectionRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-updated': typeof ApiPublicShopifyWebhooksOrdersUpdatedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/shopify': typeof AuthenticatedShopifyRoute
  '/api/auth/ensure-signup-profile': typeof ApiAuthEnsureSignupProfileRoute
  '/api/finance/unlock': typeof ApiFinanceUnlockRoute
  '/api/orders/apply-pending-intake': typeof ApiOrdersApplyPendingIntakeRoute
  '/api/orders/external-order-intake': typeof ApiOrdersExternalOrderIntakeRoute
  '/api/orders/external-order-intake-status': typeof ApiOrdersExternalOrderIntakeStatusRoute
  '/api/orders/items': typeof ApiOrdersItemsRoute
  '/api/orders/reset-all': typeof ApiOrdersResetAllRoute
  '/api/orders/restore-line-items': typeof ApiOrdersRestoreLineItemsRoute
  '/api/orders/update-costs': typeof ApiOrdersUpdateCostsRoute
  '/api/shopify/auto-remap-suggest': typeof ApiShopifyAutoRemapSuggestRoute
  '/api/shopify/backfill-order-item-costs': typeof ApiShopifyBackfillOrderItemCostsRoute
  '/api/shopify/force-update-order-item-costs': typeof ApiShopifyForceUpdateOrderItemCostsRoute
  '/api/shopify/inventory-reconciliation': typeof ApiShopifyInventoryReconciliationRoute
  '/api/shopify/recalculate-order-costs': typeof ApiShopifyRecalculateOrderCostsRoute
  '/api/shopify/refresh-inventory-source-of-truth': typeof ApiShopifyRefreshInventorySourceOfTruthRoute
  '/api/shopify/refresh-order-item-product-data': typeof ApiShopifyRefreshOrderItemProductDataRoute
  '/api/shopify/repair-missing-order-line-items': typeof ApiShopifyRepairMissingOrderLineItemsRoute
  '/api/shopify/repair-unknown-customers': typeof ApiShopifyRepairUnknownCustomersRoute
  '/api/shopify/reset-and-sync-2026-orders': typeof ApiShopifyResetAndSync2026OrdersRoute
  '/api/shopify/sync-inventory-cost': typeof ApiShopifySyncInventoryCostRoute
  '/api/shopify/sync-orders': typeof ApiShopifySyncOrdersRoute
  '/api/shopify/sync-products': typeof ApiShopifySyncProductsRoute
  '/api/shopify/sync-status': typeof ApiShopifySyncStatusRoute
  '/api/shopify/test-connection': typeof ApiShopifyTestConnectionRoute
  '/api/public/shopify/webhooks/orders-create': typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  '/api/public/shopify/webhooks/orders-updated': typeof ApiPublicShopifyWebhooksOrdersUpdatedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/areas'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/import'
    | '/inventory'
    | '/orders'
    | '/settings'
    | '/shopify'
    | '/api/auth/ensure-signup-profile'
    | '/api/finance/unlock'
    | '/api/orders/apply-pending-intake'
    | '/api/orders/external-order-intake'
    | '/api/orders/external-order-intake-status'
    | '/api/orders/items'
    | '/api/orders/reset-all'
    | '/api/orders/restore-line-items'
    | '/api/orders/update-costs'
    | '/api/shopify/auto-remap-suggest'
    | '/api/shopify/backfill-order-item-costs'
    | '/api/shopify/force-update-order-item-costs'
    | '/api/shopify/inventory-reconciliation'
    | '/api/shopify/recalculate-order-costs'
    | '/api/shopify/refresh-inventory-source-of-truth'
    | '/api/shopify/refresh-order-item-product-data'
    | '/api/shopify/repair-missing-order-line-items'
    | '/api/shopify/repair-unknown-customers'
    | '/api/shopify/reset-and-sync-2026-orders'
    | '/api/shopify/sync-inventory-cost'
    | '/api/shopify/sync-orders'
    | '/api/shopify/sync-products'
    | '/api/shopify/sync-status'
    | '/api/shopify/test-connection'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-updated'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/areas'
    | '/customers'
    | '/dashboard'
    | '/finance'
    | '/import'
    | '/inventory'
    | '/orders'
    | '/settings'
    | '/shopify'
    | '/api/auth/ensure-signup-profile'
    | '/api/finance/unlock'
    | '/api/orders/apply-pending-intake'
    | '/api/orders/external-order-intake'
    | '/api/orders/external-order-intake-status'
    | '/api/orders/items'
    | '/api/orders/reset-all'
    | '/api/orders/restore-line-items'
    | '/api/orders/update-costs'
    | '/api/shopify/auto-remap-suggest'
    | '/api/shopify/backfill-order-item-costs'
    | '/api/shopify/force-update-order-item-costs'
    | '/api/shopify/inventory-reconciliation'
    | '/api/shopify/recalculate-order-costs'
    | '/api/shopify/refresh-inventory-source-of-truth'
    | '/api/shopify/refresh-order-item-product-data'
    | '/api/shopify/repair-missing-order-line-items'
    | '/api/shopify/repair-unknown-customers'
    | '/api/shopify/reset-and-sync-2026-orders'
    | '/api/shopify/sync-inventory-cost'
    | '/api/shopify/sync-orders'
    | '/api/shopify/sync-products'
    | '/api/shopify/sync-status'
    | '/api/shopify/test-connection'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-updated'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/areas'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/finance'
    | '/_authenticated/import'
    | '/_authenticated/inventory'
    | '/_authenticated/orders'
    | '/_authenticated/settings'
    | '/_authenticated/shopify'
    | '/api/auth/ensure-signup-profile'
    | '/api/finance/unlock'
    | '/api/orders/apply-pending-intake'
    | '/api/orders/external-order-intake'
    | '/api/orders/external-order-intake-status'
    | '/api/orders/items'
    | '/api/orders/reset-all'
    | '/api/orders/restore-line-items'
    | '/api/orders/update-costs'
    | '/api/shopify/auto-remap-suggest'
    | '/api/shopify/backfill-order-item-costs'
    | '/api/shopify/force-update-order-item-costs'
    | '/api/shopify/inventory-reconciliation'
    | '/api/shopify/recalculate-order-costs'
    | '/api/shopify/refresh-inventory-source-of-truth'
    | '/api/shopify/refresh-order-item-product-data'
    | '/api/shopify/repair-missing-order-line-items'
    | '/api/shopify/repair-unknown-customers'
    | '/api/shopify/reset-and-sync-2026-orders'
    | '/api/shopify/sync-inventory-cost'
    | '/api/shopify/sync-orders'
    | '/api/shopify/sync-products'
    | '/api/shopify/sync-status'
    | '/api/shopify/test-connection'
    | '/api/public/shopify/webhooks/orders-create'
    | '/api/public/shopify/webhooks/orders-updated'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAuthEnsureSignupProfileRoute: typeof ApiAuthEnsureSignupProfileRoute
  ApiFinanceUnlockRoute: typeof ApiFinanceUnlockRoute
  ApiOrdersApplyPendingIntakeRoute: typeof ApiOrdersApplyPendingIntakeRoute
  ApiOrdersExternalOrderIntakeRoute: typeof ApiOrdersExternalOrderIntakeRoute
  ApiOrdersExternalOrderIntakeStatusRoute: typeof ApiOrdersExternalOrderIntakeStatusRoute
  ApiOrdersItemsRoute: typeof ApiOrdersItemsRoute
  ApiOrdersResetAllRoute: typeof ApiOrdersResetAllRoute
  ApiOrdersRestoreLineItemsRoute: typeof ApiOrdersRestoreLineItemsRoute
  ApiOrdersUpdateCostsRoute: typeof ApiOrdersUpdateCostsRoute
  ApiShopifyAutoRemapSuggestRoute: typeof ApiShopifyAutoRemapSuggestRoute
  ApiShopifyBackfillOrderItemCostsRoute: typeof ApiShopifyBackfillOrderItemCostsRoute
  ApiShopifyForceUpdateOrderItemCostsRoute: typeof ApiShopifyForceUpdateOrderItemCostsRoute
  ApiShopifyInventoryReconciliationRoute: typeof ApiShopifyInventoryReconciliationRoute
  ApiShopifyRecalculateOrderCostsRoute: typeof ApiShopifyRecalculateOrderCostsRoute
  ApiShopifyRefreshInventorySourceOfTruthRoute: typeof ApiShopifyRefreshInventorySourceOfTruthRoute
  ApiShopifyRefreshOrderItemProductDataRoute: typeof ApiShopifyRefreshOrderItemProductDataRoute
  ApiShopifyRepairMissingOrderLineItemsRoute: typeof ApiShopifyRepairMissingOrderLineItemsRoute
  ApiShopifyRepairUnknownCustomersRoute: typeof ApiShopifyRepairUnknownCustomersRoute
  ApiShopifyResetAndSync2026OrdersRoute: typeof ApiShopifyResetAndSync2026OrdersRoute
  ApiShopifySyncInventoryCostRoute: typeof ApiShopifySyncInventoryCostRoute
  ApiShopifySyncOrdersRoute: typeof ApiShopifySyncOrdersRoute
  ApiShopifySyncProductsRoute: typeof ApiShopifySyncProductsRoute
  ApiShopifySyncStatusRoute: typeof ApiShopifySyncStatusRoute
  ApiShopifyTestConnectionRoute: typeof ApiShopifyTestConnectionRoute
  ApiPublicShopifyWebhooksOrdersCreateRoute: typeof ApiPublicShopifyWebhooksOrdersCreateRoute
  ApiPublicShopifyWebhooksOrdersUpdatedRoute: typeof ApiPublicShopifyWebhooksOrdersUpdatedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/shopify': {
      id: '/_authenticated/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof AuthenticatedShopifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/shopify/test-connection': {
      id: '/api/shopify/test-connection'
      path: '/api/shopify/test-connection'
      fullPath: '/api/shopify/test-connection'
      preLoaderRoute: typeof ApiShopifyTestConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/sync-status': {
      id: '/api/shopify/sync-status'
      path: '/api/shopify/sync-status'
      fullPath: '/api/shopify/sync-status'
      preLoaderRoute: typeof ApiShopifySyncStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/sync-products': {
      id: '/api/shopify/sync-products'
      path: '/api/shopify/sync-products'
      fullPath: '/api/shopify/sync-products'
      preLoaderRoute: typeof ApiShopifySyncProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/sync-orders': {
      id: '/api/shopify/sync-orders'
      path: '/api/shopify/sync-orders'
      fullPath: '/api/shopify/sync-orders'
      preLoaderRoute: typeof ApiShopifySyncOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/sync-inventory-cost': {
      id: '/api/shopify/sync-inventory-cost'
      path: '/api/shopify/sync-inventory-cost'
      fullPath: '/api/shopify/sync-inventory-cost'
      preLoaderRoute: typeof ApiShopifySyncInventoryCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/reset-and-sync-2026-orders': {
      id: '/api/shopify/reset-and-sync-2026-orders'
      path: '/api/shopify/reset-and-sync-2026-orders'
      fullPath: '/api/shopify/reset-and-sync-2026-orders'
      preLoaderRoute: typeof ApiShopifyResetAndSync2026OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/repair-unknown-customers': {
      id: '/api/shopify/repair-unknown-customers'
      path: '/api/shopify/repair-unknown-customers'
      fullPath: '/api/shopify/repair-unknown-customers'
      preLoaderRoute: typeof ApiShopifyRepairUnknownCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/repair-missing-order-line-items': {
      id: '/api/shopify/repair-missing-order-line-items'
      path: '/api/shopify/repair-missing-order-line-items'
      fullPath: '/api/shopify/repair-missing-order-line-items'
      preLoaderRoute: typeof ApiShopifyRepairMissingOrderLineItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/refresh-order-item-product-data': {
      id: '/api/shopify/refresh-order-item-product-data'
      path: '/api/shopify/refresh-order-item-product-data'
      fullPath: '/api/shopify/refresh-order-item-product-data'
      preLoaderRoute: typeof ApiShopifyRefreshOrderItemProductDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/refresh-inventory-source-of-truth': {
      id: '/api/shopify/refresh-inventory-source-of-truth'
      path: '/api/shopify/refresh-inventory-source-of-truth'
      fullPath: '/api/shopify/refresh-inventory-source-of-truth'
      preLoaderRoute: typeof ApiShopifyRefreshInventorySourceOfTruthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/recalculate-order-costs': {
      id: '/api/shopify/recalculate-order-costs'
      path: '/api/shopify/recalculate-order-costs'
      fullPath: '/api/shopify/recalculate-order-costs'
      preLoaderRoute: typeof ApiShopifyRecalculateOrderCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/inventory-reconciliation': {
      id: '/api/shopify/inventory-reconciliation'
      path: '/api/shopify/inventory-reconciliation'
      fullPath: '/api/shopify/inventory-reconciliation'
      preLoaderRoute: typeof ApiShopifyInventoryReconciliationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/force-update-order-item-costs': {
      id: '/api/shopify/force-update-order-item-costs'
      path: '/api/shopify/force-update-order-item-costs'
      fullPath: '/api/shopify/force-update-order-item-costs'
      preLoaderRoute: typeof ApiShopifyForceUpdateOrderItemCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/backfill-order-item-costs': {
      id: '/api/shopify/backfill-order-item-costs'
      path: '/api/shopify/backfill-order-item-costs'
      fullPath: '/api/shopify/backfill-order-item-costs'
      preLoaderRoute: typeof ApiShopifyBackfillOrderItemCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shopify/auto-remap-suggest': {
      id: '/api/shopify/auto-remap-suggest'
      path: '/api/shopify/auto-remap-suggest'
      fullPath: '/api/shopify/auto-remap-suggest'
      preLoaderRoute: typeof ApiShopifyAutoRemapSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/update-costs': {
      id: '/api/orders/update-costs'
      path: '/api/orders/update-costs'
      fullPath: '/api/orders/update-costs'
      preLoaderRoute: typeof ApiOrdersUpdateCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/restore-line-items': {
      id: '/api/orders/restore-line-items'
      path: '/api/orders/restore-line-items'
      fullPath: '/api/orders/restore-line-items'
      preLoaderRoute: typeof ApiOrdersRestoreLineItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/reset-all': {
      id: '/api/orders/reset-all'
      path: '/api/orders/reset-all'
      fullPath: '/api/orders/reset-all'
      preLoaderRoute: typeof ApiOrdersResetAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/items': {
      id: '/api/orders/items'
      path: '/api/orders/items'
      fullPath: '/api/orders/items'
      preLoaderRoute: typeof ApiOrdersItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/external-order-intake-status': {
      id: '/api/orders/external-order-intake-status'
      path: '/api/orders/external-order-intake-status'
      fullPath: '/api/orders/external-order-intake-status'
      preLoaderRoute: typeof ApiOrdersExternalOrderIntakeStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/external-order-intake': {
      id: '/api/orders/external-order-intake'
      path: '/api/orders/external-order-intake'
      fullPath: '/api/orders/external-order-intake'
      preLoaderRoute: typeof ApiOrdersExternalOrderIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/apply-pending-intake': {
      id: '/api/orders/apply-pending-intake'
      path: '/api/orders/apply-pending-intake'
      fullPath: '/api/orders/apply-pending-intake'
      preLoaderRoute: typeof ApiOrdersApplyPendingIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/unlock': {
      id: '/api/finance/unlock'
      path: '/api/finance/unlock'
      fullPath: '/api/finance/unlock'
      preLoaderRoute: typeof ApiFinanceUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/ensure-signup-profile': {
      id: '/api/auth/ensure-signup-profile'
      path: '/api/auth/ensure-signup-profile'
      fullPath: '/api/auth/ensure-signup-profile'
      preLoaderRoute: typeof ApiAuthEnsureSignupProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/orders-updated': {
      id: '/api/public/shopify/webhooks/orders-updated'
      path: '/api/public/shopify/webhooks/orders-updated'
      fullPath: '/api/public/shopify/webhooks/orders-updated'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksOrdersUpdatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/shopify/webhooks/orders-create': {
      id: '/api/public/shopify/webhooks/orders-create'
      path: '/api/public/shopify/webhooks/orders-create'
      fullPath: '/api/public/shopify/webhooks/orders-create'
      preLoaderRoute: typeof ApiPublicShopifyWebhooksOrdersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShopifyRoute: typeof AuthenticatedShopifyRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShopifyRoute: AuthenticatedShopifyRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAuthEnsureSignupProfileRoute: ApiAuthEnsureSignupProfileRoute,
  ApiFinanceUnlockRoute: ApiFinanceUnlockRoute,
  ApiOrdersApplyPendingIntakeRoute: ApiOrdersApplyPendingIntakeRoute,
  ApiOrdersExternalOrderIntakeRoute: ApiOrdersExternalOrderIntakeRoute,
  ApiOrdersExternalOrderIntakeStatusRoute:
    ApiOrdersExternalOrderIntakeStatusRoute,
  ApiOrdersItemsRoute: ApiOrdersItemsRoute,
  ApiOrdersResetAllRoute: ApiOrdersResetAllRoute,
  ApiOrdersRestoreLineItemsRoute: ApiOrdersRestoreLineItemsRoute,
  ApiOrdersUpdateCostsRoute: ApiOrdersUpdateCostsRoute,
  ApiShopifyAutoRemapSuggestRoute: ApiShopifyAutoRemapSuggestRoute,
  ApiShopifyBackfillOrderItemCostsRoute: ApiShopifyBackfillOrderItemCostsRoute,
  ApiShopifyForceUpdateOrderItemCostsRoute:
    ApiShopifyForceUpdateOrderItemCostsRoute,
  ApiShopifyInventoryReconciliationRoute:
    ApiShopifyInventoryReconciliationRoute,
  ApiShopifyRecalculateOrderCostsRoute: ApiShopifyRecalculateOrderCostsRoute,
  ApiShopifyRefreshInventorySourceOfTruthRoute:
    ApiShopifyRefreshInventorySourceOfTruthRoute,
  ApiShopifyRefreshOrderItemProductDataRoute:
    ApiShopifyRefreshOrderItemProductDataRoute,
  ApiShopifyRepairMissingOrderLineItemsRoute:
    ApiShopifyRepairMissingOrderLineItemsRoute,
  ApiShopifyRepairUnknownCustomersRoute: ApiShopifyRepairUnknownCustomersRoute,
  ApiShopifyResetAndSync2026OrdersRoute: ApiShopifyResetAndSync2026OrdersRoute,
  ApiShopifySyncInventoryCostRoute: ApiShopifySyncInventoryCostRoute,
  ApiShopifySyncOrdersRoute: ApiShopifySyncOrdersRoute,
  ApiShopifySyncProductsRoute: ApiShopifySyncProductsRoute,
  ApiShopifySyncStatusRoute: ApiShopifySyncStatusRoute,
  ApiShopifyTestConnectionRoute: ApiShopifyTestConnectionRoute,
  ApiPublicShopifyWebhooksOrdersCreateRoute:
    ApiPublicShopifyWebhooksOrdersCreateRoute,
  ApiPublicShopifyWebhooksOrdersUpdatedRoute:
    ApiPublicShopifyWebhooksOrdersUpdatedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
